# Generated by Django 3.2.18 on 2023-03-18 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_published'),
            preserve_default=False,
        ),
    ]
