name: Vagrant test

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
          
    - name: upgrade vagrant version
      run: brew install hashicorp/tap/hashicorp-vagrant

    - name: Run vagrant up
      run: vagrant up
      
    - name: Test ssh
      run: vagrant ssh -c "echo 'hello'"

    - name: run sqlite test
      run: vagrant ssh -c "/opt/pelican/venv/bin/python /opt/pelican/manage.py test"
    
    - name: run production-like test
      run: vagrant ssh -c "/opt/pelican/venv/bin/python /opt/pelican/manage.py test core --settings=pelican.settings.production"

    - name: test for response
      run: vagrant ssh -c "wget localhost:80"
