name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        ls
        pwd
        sudo apt update
        sudo systemctl start postgresql.service
        pip install django
        sudo apt install -y python3-dev libpq-dev
        pip install psycopg2
        sudo -u postgres psql -f ./setup.sql
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test core
