name: Vagrant test

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
          
    - name: upgrade vagrant version
      run: brew install hashicorp/tap/hashicorp-vagrant

    - name: Run vagrant up
      run: vagrant up
      
    - name: Test ssh
      run: vagrant ssh -c "echo 'hello'"

    - name: run tests
      run: vagrant ssh -c "/vagrant/venv/bin/python /vagrant/manage.py test"
