name: Vagrant Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Vagrant
      run: |
        sudo apt-get update
        sudo apt-get install -y vagrant
    - name: Run Vagrant up
      run: |
        vagrant up
